### ISSUE TITLE
error 502

### ISSUE THREAD

**Issue by lassancejm** [dave-the-scientist/miphy#7]
Hi, 

I am trying to run MIPhy on a large gene tree (~ 3000 leaves) with data coming from 3 species. 
Using the webserver, I encountered an error 502. I attempted to get more details about what might cause the error and moved to the command line version, which I am running on Mac OS X. 
I am getting the following error: 

```
File "/Users/jm/opt/anaconda3/lib/python3.8/site-packages/miphy_resources/phylo.py", line 681, in parse_newick
    parent_nodes[-1].children.append(node)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jm/opt/anaconda3/bin/miphy.py", line 181, in <module>
    idnum = daemon.new_instance(gene_tree_data, info_data, gene_tree_format=options['tree_format'], merge_singletons=merge_singles, use_coords=options['use_coords'], coords_file=options['coords_file'])
  File "/Users/jm/opt/anaconda3/lib/python3.8/site-packages/miphy_resources/miphy_daemon.py", line 288, in new_instance
    self.sessions[idnum] = MiphyInstance(gene_tree_data, info_data, gene_tree_format, self.allowed_wait, merge_singletons, use_coords, coords_file, self.verbose, refine_limit=self.server_refine_limit)
  File "/Users/jm/opt/anaconda3/lib/python3.8/site-packages/miphy_resources/miphy_instance.py", line 32, in __init__
    self.clusterer = Clusterer(gene_tree, self.species_tree_data, self.species_mapping, use_coords, coords_file, self.verbose)
  File "/Users/jm/opt/anaconda3/lib/python3.8/site-packages/miphy_resources/clusterer.py", line 22, in __init__
    self.parse_species_tree(species_tree_data)
  File "/Users/jm/opt/anaconda3/lib/python3.8/site-packages/miphy_resources/clusterer.py", line 84, in parse_species_tree
    spc_tree = phylo.load_newick_string(species_tree_data)
  File "/Users/jm/opt/anaconda3/lib/python3.8/site-packages/miphy_resources/phylo.py", line 156, in load_newick_string
    tree.parse_newick(tree_string, internal_as_names)
  File "/Users/jm/opt/anaconda3/lib/python3.8/site-packages/miphy_resources/phylo.py", line 687, in parse_newick
    raise PhyloParseError('Error: malformed Newick data.')
```
The tree was produced by iqtree. As it was unrooted, I applied midpoint rooting using Figtree. As far as I can tell, the file is not malformed (figtree can re-open it fine). I am wondering if you could have a look. Also, I am curious to hear whether it is worth trying to do this analysis with a very limited number of species. 

Thanks!

JML

[Olfr_info.txt](https://github.com/user-attachments/files/16886372/Olfr_info.txt)
[Olfr_ALL.mafft.fasta.withIDS.midroot.txt](https://github.com/user-attachments/files/16886373/Olfr_ALL.mafft.fasta.withIDS.midroot.txt)

**Comment by dave-the-scientist** [comment]
Hi JML, apologies for the delay I should be able to get to this early next week.
